version: "3.8"

services:
    db:
        image: mongo:4.2
        volumes:
            - manuf-sim-db-vol:/data/db
        restart: unless-stopped
        
    backend-server:
        depends_on:
            - "db"
        image: manuf-sim-backend-server
        build:
            context: ..
            dockerfile: ./docker/backend-server/Dockerfile
        ports:
            - "${BACKEND_PORT:-3000}:3000"
        restart: unless-stopped
    
    frontend-server:
        depends_on:
            - "backend-server"
        image: manuf-sim-frontend-server
        build:
            context: ..
            dockerfile: ./docker/frontend-server/Dockerfile
        ports:
            - "${FRONTEND_PORT:-80}:8080"
        restart: unless-stopped

volumes:
    manuf-sim-db-vol: